# Generated by Django 4.2.2 on 2023-07-12 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('urlimage', models.URLField(blank=True, max_length=512)),
                ('uploadimage', models.ImageField(blank=True, default='uploads/default.jpg', upload_to='uploads/')),
                ('statusActive', models.BooleanField(default=True)),
                ('dirtyHack', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorUser', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='auctions.category')),
                ('usersWhoAddToWatchlist', models.ManyToManyField(blank=True, related_name='watchingUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userBid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.lot')),
            ],
        ),
    ]
